### PR TITLE
HOTFIX fix logo animation from gif to animated png

### PR DESCRIPTION
**Pull request by Encall**
lgtm
need test for some mac device

### CODE REVIEW

**Comment by sokungz01** [comment]
by some browser have a blue logo issue
Screen Shot 2566-02-06 at 20 43 21

**Comment by Encall** [comment]
> by some browser have a blue logo issue
> 
> have this issue on `Safari Version 16.0 (17614.1.25.9.10, 17614)` MacBook x86 Screen Shot 2566-02-06 at 20 43 21

your macbook is shit

**Comment by sokungz01** [comment]
> > by some browser have a blue logo issue
> > have this issue on `Safari Version 16.0 (17614.1.25.9.10, 17614)` MacBook x86 Screen Shot 2566-02-06 at 20 43 21
> 
> your macbook is shit

bruh maybe it is edge case

**Review by sokungz01 — APPROVED** [review]
LGTM

**Pull request merged**
