### PR TITLE
feat:TimelineSection

### PR DESCRIPTION
**Pull request by Etantj**
image

### CODE REVIEW

**Comment by sokungz01** [comment]
Screen Shot 2566-02-07 at 21 48 54
Screen Shot 2566-02-07 at 21 49 27
Screen Shot 2566-02-07 at 21 50 10

**Comment by sokungz01** [comment]
Background

**Comment by sokungz01** [comment]
Screen Shot 2566-02-07 at 21 54 28

**Review by SSSBoOm — APPROVED** [review]

**Pull request merged**
